version: "3"
services:

  authoremicroservice:
    build: 
      context: ./demo-authormicroservice
      dockerfile: Dockerfile.native
    container_name: authorservice
    healthcheck:
      test: curl -f http://localhost/health || exit 1
    ports:
      - "8081:8081"
   

  quotemicroservice:
    build: 
      context: ./demo-quoteservice
      dockerfile: Dockerfile.native
    container_name: quoteservice
    ports:
      - "8082:8080"
    environment:
      AUTHOR_SERVICE: http://authoremicroservice:8081

    depends_on:
      - authoremicroservice

  apicompositionmicroservice:
    build: 
      context: ./demo-quotecompositionservice
      dockerfile: Dockerfile.native
    container_name: quotecompositionservice
    healthcheck:
      test: curl -f http://localhost:8081/health/ready || exit 1
    ports:
      - "8080:8082"
    environment:
      AUTHOR_SERVICE: http://authoremicroservice:8081
      QUOTE_SERVICE: http://quotemicroservice:8080
    depends_on:
      quotemicroservice:
        condition: service_healty
      authoremicroservice:
        condition: service_healty
    

  