apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: tp-monitoring
spec:
  type: ClusterIP
  selector:
    name: mysql
  ports:
  #-- port du service
  - port: 3306
  #-- port du conteneur
    targetPort: 3306
    protocol: TCP
    name: port-mysql
