apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tp-kubernetes
spec:
  type: ClusterIP
  selector:
    app: tp-redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: port-redis
  
