apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
 #-- selection du pod par le label
spec:
  selector:
    matchLabels:
      app: nginx
  #--pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
 
    