---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rest-villains
spec:
  lookupPolicy:
    local: false
  tags:
    - name: java11-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:java11-latest'
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: java17-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:java17-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
    - name: native-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/rest-villains:native-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
