apiVersion: v1
kind: Service
metadata:
  name: serviceapp2
spec:
  type: ClusterIP
  selector:
    name: app2
  ports:
  #-- port du service
  - port: 3001
  #-- port du conteneur
    targetPort: 3001
    protocol: TCP
    name: http-port