apiVersion: v1
kind: Service
metadata:
  name: serviceapp1
spec:
  type: NodePort
  selector:
    name: app1
  ports:
  #-- port du service
  - port: 3002
  #-- port du conteneur
    targetPort: 3000
    protocol: TCP
    nodePort: 30001
    name: http-port