apiVersion: v1
kind: Service
metadata:
  name: service-kibana
  namespace: tp-monitoring
spec:
  type: NodePort
  selector:
    name: kibana
  ports:
  #-- port du service cluster IP
  - port: 5601
  #-- port du conteneur
    targetPort: 5601
    protocol: TCP
  #--- Port d'un service node port entre 30000 et 32767
    nodePort: 30001
    name: http-port
  
