apiVersion: v1
kind: Service
metadata:
  name: clusterip-http-service
spec:
  type: ClusterIP
  selector:
    app: nginx-app
  ports:
  #-- port du service
  - port: 1000
  #-- port du conteneur
    targetPort: 80
    protocol: TCP
    name: http-port
  - port: 1001
    targetPort: 443
    protocol: TCP
    name: https-port