apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-volume
  labels:
    storage: elastic-storage
  namespace: tp-monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    path: /data-monitoring
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-volume-claim
spec:
  storageClassName: standard
  selector:
    matchLabels:
      storage: elastic-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

