apiVersion: v1
kind: Pod
metadata:
  name: busyboxpod
  labels:
    name: myapp
spec:
  containers:
  - name: busyboxcontainer
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "100m"
    command: ["sh", "-c", "echo $MESSAGE && sleep 3600"]
    
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          key: MESSAGE
          name: myapp-config
    
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          key: PASSWORD
          name: myapp-secret